### ISSUE TITLE
01-sasl-and-tls/docker-compose.yml is broken

### ISSUE THREAD

**Issue by pvspain** [redpanda-data-university/05-redpanda-field-guide#5]
The `connect:image` value in `01-sasl-and-tls/docker-compose.yml` needs updating

```yaml
  connect:
    image: docker.cloudsmith.io/redpanda/connectors/connectors:624ff9e
    hostname: connect
    container_name: connect
```
